cacheType: badger

redis:
  nodes: "127.0.0.1:6379"
  password: "yourpass"
  prefixKey: "vapi:"
  timeout: 5s
  db: 0

memcached:
  nodes: "127.0.0.1:11211"

badger:
  path: "./tmp/badger"

inmemory:
  defaultTTL: 5m
  cleanupInterval: 10m

driverType: mysql

database:
  #driver: "mysql"
  #dsn: "root:123456@tcp(localhost:3306)/tenant_manager?charset=utf8mb4&parseTime=True&loc=Local&timeout=10s&multiStatements=true"
  manager: tenant_manager
  driver: sqlserver
  dsn: sqlserver://sa:123456@localhost:1433?database=tenant_manager

host: 0.0.0.0
port: 8012
#FileName   string `mapstructure:"fileName"`
#MaxSize    int    `mapstructure:"maxSize"`
#MaxAge     int    `mapstructure:"maxAge"`
#MaxBackups int    `mapstructure:"maxBackups"`
#Compress   bool   `mapstructure:"compress"`
#AlsoStdout bool   `mapstructure:"alsoStdout"`
log:
  path: ./logs/server.log
  maxSize: 2 #2MB
  maxAge: 7 #7 days
  maxBackups: 30
  compress: true
  alsoStdout: true
  