// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: invoker/invoker.proto

package invoker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Invoker_Invoke_FullMethodName = "/invoker.Invoker/Invoke"
)

// InvokerClient is the client API for Invoker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvokerClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error)
}

type invokerClient struct {
	cc grpc.ClientConnInterface
}

func NewInvokerClient(cc grpc.ClientConnInterface) InvokerClient {
	return &invokerClient{cc}
}

func (c *invokerClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, Invoker_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvokerServer is the server API for Invoker service.
// All implementations must embed UnimplementedInvokerServer
// for forward compatibility.
type InvokerServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeReply, error)
	mustEmbedUnimplementedInvokerServer()
}

// UnimplementedInvokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvokerServer struct{}

func (UnimplementedInvokerServer) Invoke(context.Context, *InvokeRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInvokerServer) mustEmbedUnimplementedInvokerServer() {}
func (UnimplementedInvokerServer) testEmbeddedByValue()                 {}

// UnsafeInvokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvokerServer will
// result in compilation errors.
type UnsafeInvokerServer interface {
	mustEmbedUnimplementedInvokerServer()
}

func RegisterInvokerServer(s grpc.ServiceRegistrar, srv InvokerServer) {
	// If the following call pancis, it indicates UnimplementedInvokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Invoker_ServiceDesc, srv)
}

func _Invoker_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invoker_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Invoker_ServiceDesc is the grpc.ServiceDesc for Invoker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Invoker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoker.Invoker",
	HandlerType: (*InvokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Invoker_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoker/invoker.proto",
}
