// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: invoker/invoker.proto

package invoker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackagePath   string                 `protobuf:"bytes,1,opt,name=packagePath,proto3" json:"packagePath,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_invoker_invoker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoker_invoker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_invoker_invoker_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

func (x *InvokeRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *InvokeRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type InvokeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Struct       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeReply) Reset() {
	*x = InvokeReply{}
	mi := &file_invoker_invoker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeReply) ProtoMessage() {}

func (x *InvokeReply) ProtoReflect() protoreflect.Message {
	mi := &file_invoker_invoker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeReply.ProtoReflect.Descriptor instead.
func (*InvokeReply) Descriptor() ([]byte, []int) {
	return file_invoker_invoker_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeReply) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_invoker_invoker_proto protoreflect.FileDescriptor

const file_invoker_invoker_proto_rawDesc = "" +
	"\n" +
	"\x15invoker/invoker.proto\x12\ainvoker\x1a\x1cgoogle/protobuf/struct.proto\"\x86\x01\n" +
	"\rInvokeRequest\x12 \n" +
	"\vpackagePath\x18\x01 \x01(\tR\vpackagePath\x12\"\n" +
	"\ffunctionName\x18\x02 \x01(\tR\ffunctionName\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\">\n" +
	"\vInvokeReply\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result2A\n" +
	"\aInvoker\x126\n" +
	"\x06Invoke\x12\x16.invoker.InvokeRequest\x1a\x14.invoker.InvokeReplyB\vZ\t./invokerb\x06proto3"

var (
	file_invoker_invoker_proto_rawDescOnce sync.Once
	file_invoker_invoker_proto_rawDescData []byte
)

func file_invoker_invoker_proto_rawDescGZIP() []byte {
	file_invoker_invoker_proto_rawDescOnce.Do(func() {
		file_invoker_invoker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoker_invoker_proto_rawDesc), len(file_invoker_invoker_proto_rawDesc)))
	})
	return file_invoker_invoker_proto_rawDescData
}

var file_invoker_invoker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_invoker_invoker_proto_goTypes = []any{
	(*InvokeRequest)(nil),   // 0: invoker.InvokeRequest
	(*InvokeReply)(nil),     // 1: invoker.InvokeReply
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_invoker_invoker_proto_depIdxs = []int32{
	2, // 0: invoker.InvokeRequest.params:type_name -> google.protobuf.Struct
	2, // 1: invoker.InvokeReply.result:type_name -> google.protobuf.Struct
	0, // 2: invoker.Invoker.Invoke:input_type -> invoker.InvokeRequest
	1, // 3: invoker.Invoker.Invoke:output_type -> invoker.InvokeReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_invoker_invoker_proto_init() }
func file_invoker_invoker_proto_init() {
	if File_invoker_invoker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoker_invoker_proto_rawDesc), len(file_invoker_invoker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invoker_invoker_proto_goTypes,
		DependencyIndexes: file_invoker_invoker_proto_depIdxs,
		MessageInfos:      file_invoker_invoker_proto_msgTypes,
	}.Build()
	File_invoker_invoker_proto = out.File
	file_invoker_invoker_proto_goTypes = nil
	file_invoker_invoker_proto_depIdxs = nil
}
