storage:
  type: local
  location: ./uploads
server:
  port: "8080"
  bind: "0.0.0.0"
  mode: "debug"
database:
  
  dsn1: "postgres://postgres:123456@localhost:5432/a001?sslmode=disable"
  driver1: postgres
  dsn: "root:123456@tcp(localhost:3306)/a001"
  driver: mysql
jwt:
  secret: "dadada.dasd.das.ada.dad.sada.dadad.dad"
  ttl:
    access: 30m
    refresh: 168h