app:
  name: MyGoAPI
  version: 1.0.0
database:
  driver: "mssql"
  host: "localhost"
  port: 0
  user: "sa"
  password: "123456"
  ssl: false
  name: "mygoapi"

 
server:
  bind: "0.0.0.0"
  port: 8080
  debug_mode: true
cache: bagger
barger: unvs
memcached:
  - localhost:11211
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  timeout: 50
logs: ./logs/app.log
    


