app:
  name: MyGoAPI
  version: 1.0.0
database:
  driver: "mssql"
  host: "localhost"
  port: 1433
  user: "sa"
  password: "123456"
  ssl: false
  name: "mygoapi"

 
server:
  port: 8080
  debug_mode: true