// Code generated by ent, DO NOT EDIT.

package ent

import (
	"check/ent/order"
	"check/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescNote is the schema descriptor for note field.
	orderDescNote := orderFields[2].Descriptor()
	// order.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	order.NoteValidator = orderDescNote.Validators[0].(func(string) error)
	// orderDescCreatedBy is the schema descriptor for created_by field.
	orderDescCreatedBy := orderFields[5].Descriptor()
	// order.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	order.CreatedByValidator = orderDescCreatedBy.Validators[0].(func(string) error)
	// orderDescUpdatedBy is the schema descriptor for updated_by field.
	orderDescUpdatedBy := orderFields[6].Descriptor()
	// order.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	order.UpdatedByValidator = orderDescUpdatedBy.Validators[0].(func(string) error)
}
