basePath: /api/v1
definitions:
  accounts.CreateAccountRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  accounts.CreateAccountResponse:
    properties:
      message:
        type: string
      user:
        $ref: '#/definitions/unvs_internal_model_auth.User'
    type: object
  accounts.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  accounts.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  accounts.LoginResponse:
    properties:
      message:
        type: string
      token:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/unvs_internal_model_auth.User'
        description: Có thể bao gồm thêm thông tin người dùng nếu cần, nhưng không
          phải mật khẩu hash
    type: object
  internal_app_handler_callers.CallerRequest:
    properties:
      args: {}
      language:
        type: string
      tenant:
        type: string
    type: object
  internal_app_handler_callers.CallerResponse:
    properties:
      error:
        $ref: '#/definitions/internal_app_handler_callers.ErrorResponse'
      results: {}
    type: object
  internal_app_handler_callers.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  internal_app_handler_inspector.InspectorResponse:
    properties:
      apiList:
        items:
          type: string
        type: array
    type: object
  unvs_internal_model_auth.User:
    properties:
      createdAt:
        type: string
      createdBy:
        type: string
      description:
        type: string
      email:
        type: string
      failedLoginCount:
        type: integer
      isLocked:
        type: boolean
      isSupperUser:
        type: boolean
      lastFailedLoginAt:
        type: string
      lastLoginAt:
        type: string
      lastPasswordChangeAt:
        type: string
      roleId:
        type: integer
      updatedAt:
        type: string
      updatedBy:
        type: string
      userId:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: '"OAuth2 Password Flow (Form Submit) - Use for explicit form data submission."'
  title: Go API Example
  version: "1.0"
paths:
  /accounts/create:
    post:
      consumes:
      - application/json
      description: Tạo một tài khoản người dùng mới với username, email và mật khẩu.
      parameters:
      - description: tên của Tenant
        in: path
        name: tenant
        required: true
        type: string
      - description: Thông tin tài khoản cần tạo
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/accounts.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Tạo tài khoản thành công
          schema:
            $ref: '#/definitions/accounts.CreateAccountResponse'
        "400":
          description: Yêu cầu không hợp lệ (validation errors)
          schema:
            $ref: '#/definitions/accounts.ErrorResponse'
        "409":
          description: Email đã tồn tại
          schema:
            $ref: '#/definitions/accounts.ErrorResponse'
        "500":
          description: Lỗi nội bộ server
          schema:
            $ref: '#/definitions/accounts.ErrorResponse'
      security:
      - OAuth2Password: []
      summary: Tạo một tài khoản người dùng mới
      tags:
      - Accounts
  /accounts/login:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: Xác thực thông tin đăng nhập của người dùng (email hoặc username)
        và trả về JWT token nếu thành công.
      parameters:
      - description: Thông tin đăng nhập (email/username và mật khẩu)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/accounts.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Đăng nhập thành công, trả về JWT token
          schema:
            $ref: '#/definitions/accounts.LoginResponse'
        "400":
          description: Yêu cầu không hợp lệ (validation errors)
          schema:
            $ref: '#/definitions/accounts.ErrorResponse'
        "401":
          description: Thông tin đăng nhập không hợp lệ
          schema:
            $ref: '#/definitions/accounts.ErrorResponse'
        "500":
          description: Lỗi nội bộ server
          schema:
            $ref: '#/definitions/accounts.ErrorResponse'
      summary: Đăng nhập người dùng và nhận JWT token (JSON/Form)
      tags:
      - Accounts
  /hz:
    get:
      consumes:
      - application/json
      description: Trả về chuỗi "Hello World!"
      produces:
      - application/json
      responses:
        "200":
          description: Hello World!
          schema:
            type: string
      summary: Lấy một lời chào đơn giản
      tags:
      - heathz
    post:
      consumes:
      - application/json
      description: Endpoint check the accessibility.
      responses: {}
      summary: Health check endpoint
      tags:
      - Healthz
  /inspector/list:
    post:
      consumes:
      - application/json
      description: Query all api action and domain
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_app_handler_inspector.InspectorResponse'
      summary: Query all api action and domain
      tags:
      - System
  /invoke/{action}:
    post:
      consumes:
      - application/json
      description: CallerHandler
      parameters:
      - description: The specific action to invoke (e.g., login, register, logout)
        in: path
        name: action
        required: true
        type: string
      - description: CallerRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_app_handler_callers.CallerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Response
          schema:
            $ref: '#/definitions/internal_app_handler_callers.CallerResponse'
      security:
      - OAuth2Password: []
      summary: CallerHandler
      tags:
      - caller
  /oauth/token:
    post:
      responses: {}
securityDefinitions:
  OAuth2Password:
    description: '"OAuth2 Password Flow - Enter email/username and password in the
      popup to get token."'
    flow: password
    tokenUrl: /oauth/token
    type: oauth2
swagger: "2.0"
