[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"

[dependencies]

actix-web = "4"
serde_json = "1.0"
walkdir = "2.3"
futures-util = "0.3"
tokio = { version = "1.36", features = ["full"] }
tokio-stream = "0.1"