// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: caller/caller.proto

package caller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message để đóng gói một slice của các Any
type AnyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*anypb.Any           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyList) Reset() {
	*x = AnyList{}
	mi := &file_caller_caller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyList) ProtoMessage() {}

func (x *AnyList) ProtoReflect() protoreflect.Message {
	mi := &file_caller_caller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyList.ProtoReflect.Descriptor instead.
func (*AnyList) Descriptor() ([]byte, []int) {
	return file_caller_caller_proto_rawDescGZIP(), []int{0}
}

func (x *AnyList) GetValues() []*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

// Yêu cầu để gọi hàm
type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodPath    string                 `protobuf:"bytes,1,opt,name=method_path,json=methodPath,proto3" json:"method_path,omitempty"`
	InputJson     []byte                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_caller_caller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_caller_caller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_caller_caller_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeRequest) GetMethodPath() string {
	if x != nil {
		return x.MethodPath
	}
	return ""
}

func (x *InvokeRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

// Phản hồi từ hàm
type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_caller_caller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_caller_caller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_caller_caller_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_caller_caller_proto protoreflect.FileDescriptor

const file_caller_caller_proto_rawDesc = "" +
	"\n" +
	"\x13caller/caller.proto\x12\n" +
	"rpcservice\x1a\x19google/protobuf/any.proto\"7\n" +
	"\aAnyList\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\x06values\"O\n" +
	"\rInvokeRequest\x12\x1f\n" +
	"\vmethod_path\x18\x01 \x01(\tR\n" +
	"methodPath\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\fR\tinputJson\"M\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2J\n" +
	"\aInvoker\x12?\n" +
	"\x06Invoke\x12\x19.rpcservice.InvokeRequest\x1a\x1a.rpcservice.InvokeResponseB\n" +
	"Z\b./callerb\x06proto3"

var (
	file_caller_caller_proto_rawDescOnce sync.Once
	file_caller_caller_proto_rawDescData []byte
)

func file_caller_caller_proto_rawDescGZIP() []byte {
	file_caller_caller_proto_rawDescOnce.Do(func() {
		file_caller_caller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_caller_caller_proto_rawDesc), len(file_caller_caller_proto_rawDesc)))
	})
	return file_caller_caller_proto_rawDescData
}

var file_caller_caller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_caller_caller_proto_goTypes = []any{
	(*AnyList)(nil),        // 0: rpcservice.AnyList
	(*InvokeRequest)(nil),  // 1: rpcservice.InvokeRequest
	(*InvokeResponse)(nil), // 2: rpcservice.InvokeResponse
	(*anypb.Any)(nil),      // 3: google.protobuf.Any
}
var file_caller_caller_proto_depIdxs = []int32{
	3, // 0: rpcservice.AnyList.values:type_name -> google.protobuf.Any
	1, // 1: rpcservice.Invoker.Invoke:input_type -> rpcservice.InvokeRequest
	2, // 2: rpcservice.Invoker.Invoke:output_type -> rpcservice.InvokeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_caller_caller_proto_init() }
func file_caller_caller_proto_init() {
	if File_caller_caller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_caller_caller_proto_rawDesc), len(file_caller_caller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caller_caller_proto_goTypes,
		DependencyIndexes: file_caller_caller_proto_depIdxs,
		MessageInfos:      file_caller_caller_proto_msgTypes,
	}.Build()
	File_caller_caller_proto = out.File
	file_caller_caller_proto_goTypes = nil
	file_caller_caller_proto_depIdxs = nil
}
